### ISSUE TITLE
Bypassing ajax navigation (in commerce 0.11.0)

### ISSUE THREAD

**Issue by Mark-H** [digitalpenguin/Commerce_MultiLang#2]
Per one of your feature requests, Commerce 0.11.0-pl has a new class you can add to a link (including nav items) to prevent it from using the ajax navigation. This class is `commerce-ignore-jsnav` and needs to be added to the link or nav item.

I don't have MultiLang installed locally, but [here](https://github.com/digitalpenguin/CommerceMultiLang/blob/master/core/components/commercemultilang/src/Modules/CommerceMultiLang.php#L34) you should add:

````
            $items['products']['link'] = '?namespace=commercemultilang&a=home';
            $items['products']['class'] = 'commerce-ignore-jsnav';
````

which should do the trick. 

[modmore/Commerce#277]

**Comment by muzzwood** [comment]
Brilliant! Thanks!
